# Generated by Django 5.0.4 on 2024-07-26 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_postdaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(default=django.utils.timezone.now, verbose_name='期日')),
                ('task', models.CharField(max_length=10, verbose_name='タスク名')),
            ],
        ),
        migrations.AlterField(
            model_name='postdaily',
            name='days',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
